[.text-justify]
= Daiyousei
:source-highlighter: rouge
:table-caption!:

Daiyousei is a lightweight and efficient program, the purpose of which is act as a different process.

It has two primary responsibilities:

* Passing its own execution context, environment, arguments and standard input to the remote process.
* Receiving and printing the standard and error outputs and returning the exit code received from the remote process.

The use case for this program is in the following situation:

* There is a server process running which has single or more responsibilities.
* The server can be extended to communicate using the Bencode encoding.
* The simplest way to send requests is by spawning (this) process.

== Building
The project is written in C{plus}{plus} and requires a C{plus}{plus} compiler supporting the language version 23.
Build instructions are managed in the `Makefile`.

Build the project by running:
----
make compile
----

=== Testing
The following targets use extended compile and link flags, adding Address Sanitizer and Undefined Behavior Sanitizer.
In order to make sure everything is built with these flags, you may need to clean the project:
----
make clean
----

Run unit tests also written in C{plus}{plus}:
----
make test-unit
----

Run tests using a server written in Python:
----
make test-server
----

=== Coverage
There is a `coverage` target which adds additional compile and link flags (note about cleaning the project) and runs the tests.
----
make coverage
----

The generated report can be viewed in `target/coverage/index.html`.

=== Building documentation
Documentation is built using `asciidoctor`.

Build HTML documentation and place it in `target/doc`:
----
make doc
----

Build manual pages and place them in `target/manpages`:
----
make manpages
----

== Specification
See the https://mkoncek.github.io/daiyousei[full documentation] describing runtime behaviour in detail.
