[.text-justify]
= Daiyousei
:toc: left
:source-highlighter: rouge
:table-caption!:

A lightweight intermediary for running processes.

Daiyousei is a lightweight program the purpose of which is act as a different process.
Upon starting, it connects to a running, listening program, referred to as _server_, via a socket.
Then daiyousei, in this context the _client_, transparently sends and receives fundamental runtime execution data.
The data include the environment context, arguments, standard input / output streams and the exit code.

== Running
When the program starts, the communication channel needs to be already created and the server needs to be listening for connections.
The client and server then communicate and after the communication is finished.

If no error is encountered by the client, the exit code from the server is returned.
In case of an internal error, the programs attempts to return the value `255`, though this may not be guaranteed.

=== Options
The tool does not use any command-line arguments.
All arguments are passed over the communication channel.
The tool requires the first argument, i.e. the executable name, also known as `argv[0]`, to be valid.

=== Environment variables
The tool can be configured using the following environment variables:

[cols = 2]
[%autowidth]
|===
|Name|Description

|`DAIYOUSEI_UNIX_SOCKET`|File path of the Unix socket that will be used for communication
|===

== Communication
All communication is encoded in the https://en.wikipedia.org/wiki/Bencode[Bencode] encoding.
Both parties communicate by sending a single list to each other.
The start of the list means initiating communication and the list end means proper termination of communication.
The list contains key-value pairs, similar to a dictionary but the keys can be repeated.

=== Socket path
Currently only Unix domain stream socket communication is supported.

The Unix socket file path used for communication is selected using the following procedure:

* If the variable `DAIYOUSEI_UNIX_SOCKET` is defined, it is used.
* Otherwise if `XDG_RUNTIME_DIR` is defined, the socket `daiyousei.sock` inside the directory is used.
* Otherwise the socket `daiyousei.sock` inside the `/tmp` directory is used.

=== Protocol
The communication protocol used by the communicating parties as follows.

==== Client to server
When the client starts, it immediately sends its command-line arguments, current working directory and the environment variables over the communication channel.
Standard input is sent in chunks as the program receives it.
When the standard input is closed on the client side, it sends the closing end of the list and closes the connection.

[cols = "1a,1a"]
[frame = "none"]
[grid = "cols"]
[%autowidth]
|===
|.BNF notation, client-to-server protocol
[cols = ">1,^1,1"]
[frame = "all"]
[grid = "rows"]
[%autowidth]
!===
!`[green]#Request#`!`::=`!`[red]#"l"# [green]#Argv# [green]#Cwd# [green]#Env# [green]#Stdin# [red]#"e"#`
!`[green]#Argv#`!`::=`!`[red]#"4:argv"# [red]#"l"# [green]#Args# [red]#"e"#`
!`[green]#Args#`!`::=`!`[green]#Ben-string#`
!`[green]#Args#`!`::=`!`[green]#Args# [green]#Ben-string#`
!`[green]#Cwd#`!`::=`!`[red]#"3:cwd"# [green]#Ben-string#`
!`[green]#Env#`!`::=`!`[red]#"3:env"# [red]#"l"# [green]#Pairs# [red]#"e"#`
!`[green]#Pairs#`!`::=`!
!`[green]#Pairs#`!`::=`!`[green]#Pairs# [green]#Ben-string# [green]#Ben-string#`
!`[green]#Stdin#`!`::=`!
!`[green]#Stdin#`!`::=`!`[green]#Stdin# [red]#"5:stdin"# [green]#Ben-string#`
!===
|.Extended BNF notation, client-to-server protocol
[cols = ">1,^1,1"]
[frame = "all"]
[grid = "rows"]
[%autowidth]
!===
!`[green]#request#`!`=`!`[red]#"l"#, [green]#argv#, [green]#cwd#, [green]#env#, { [green]#stdin# }, [red]#"e"#;`
!`[green]#argv#`!`=`!`[red]#"4:argv"#, [red]#"l"#, { [green]#ben-string# }, [red]#"e"#;`
!`[green]#cwd#`!`=`!`[red]#"3:cwd"#, [green]#ben-string#;`
!`[green]#env#`!`=`!`[red]#"3:env"#, [red]#"l"#, { [green]#ben-string#, [green]#ben-string# }, [red]#"e"#;`
!`[green]#stdin#`!`=`!`[red]#"5:stdin"#, [green]#ben-string#;`
!===
|===

==== Server to client
The server communicates by sending its outputs in chunks and the exit code as the last value.
The exit code is returned by the client program unless it encounters a different error.

[cols = "1a,1a"]
[frame = "none"]
[grid = "cols"]
[%autowidth]
|===
|.BNF notation, server-to-client protocol
[cols = ">1,^1,1"]
[frame = "all"]
[grid = "rows"]
[%autowidth]
!===
!`[green]#Response#`!`::=`!`[red]#"l"# [green]#Chunk# [green]#Exit# [red]#"e"#`
!`[green]#Chunk#`!`::=`!`[red]#"6:stdout"# [green]#Ben-string#`
!`[green]#Chunk#`!`::=`!`[red]#"6:stderr"# [green]#Ben-string#`
!`[green]#Exit#`!`::=`!`[red]#"8:exitcode"# [green]#Ben-integer#`
!===
|.Extended BNF notation, server-to-client protocol
[cols = ">1,^1,1"]
[frame = "all"]
[grid = "rows"]
[%autowidth]
!===
!`[green]#response#`!`=`!`[red]#"l"#, { [green]#stdout# \| [green]#stderr# }, [green]#exitcode#, [red]#"e"#;`
!`[green]#stdout#`!`=`!`[red]#"6:stdout"#, [green]#ben-string#;`
!`[green]#stderr#`!`=`!`[red]#"6:stderr"#, [green]#ben-string#;`
!`[green]#exitcode#`!`=`!`[red]#"8:exitcode"#, [green]#ben-integer#;`
!===
|===

=== Termination
The client will keep listening until the server sends the end-of-list.
After that, the client will attempt to `shutdown(2)` and `close(2)` the socket regardless of whether or not the server closes the socket.
