[.text-justify]
= Daiyousei
:toc: left
:source-highlighter: rouge
:table-caption!:

TODO.

== Running
When the program starts, the communication channel needs to be already created and the server needs to be listening for connections.
The client and server then communicate and after the communication is finished.

If no error is encountered by the client, the exit code from the server is returned.
In case of an internal error, the programs attempts to return the value `255`, though this may not be guaranteed.

=== Command-line arguments
The tool does not use any command-line arguments.
All arguments are passed over the communication channel.
The tool requires the first argument, i.e. the executable name, also known as `argv[0]`, to be valid.

=== Environment variables
The tool can be configured using the following environment variables.

[cols = 2]
[%autowidth]
|===
|Name|Description

|`DAIYOUSEI_UNIX_SOCKET`|File path of the Unix socket that will be used for communication
|===

== Communication
All communication is encoded in the https://en.wikipedia.org/wiki/Bencode[Bencode] encoding.
Both parties communicate by sending a single list to each other.
The start of the list means initiating communication and the list end means proper termination of communication.
The list contains key-value pairs, similar to a dictionary but the keys can be repeated.

=== Socket path
The Unix socket file path used for communication is selected using the following procedure.

* If the variable `DAIYOUSEI_UNIX_SOCKET` is defined, it is used.
* Otherwise if `XDG_RUNTIME_DIR` is defined, the socket `daiyousei.sock` is created inside the directory.
* Otherwise the socket is created inside `/tmp`.

=== Protocol
The communication protocol used by the communicating parties as follows.

==== From client to server
When the client starts, it immediately sends its command-line arguments, current working directory and the environment variables over the communication channel.
Standard input is sent in chunks as the program receives it.
When the standard input is closed on the client side, it sends the closing end of the list and closes the connection.

.BNF notation of the client-to-server communication protocol
[cols = ">1,^1,1"]
[frame = "all"]
[grid = "rows"]
[%autowidth]
|===
|`Request`|`::=`|`"l"` `Argv` `Cwd` `Env` `Stdin` `"e"`
|`Argv`|`::=`|`"4:argv"` `"l"` `Args` `"e"`
|`Args`|`::=`|`Ben-string`
|`Args`|`::=`|`Args` `Ben-string`
|`Cwd`|`::=`|`"3:cwd"` `Ben-string`
|`Env`|`::=`|`"3:env"` `"l"` `Pairs` `"e"`
|`Pairs`|`::=`|
|`Pairs`|`::=`|`Pairs` `Ben-string` `Ben-string`
|`Stdin`|`::=`|
|`Stdin`|`::=`|`Stdin` `"5:stdin"` `Ben-string`
|===

==== From server to client
The server communicates by sending its outputs in chunks and the exit code as the last value.
The exit code is returned by the client program unless it encounters a different error.

.BNF notation of the server-to-client communication protocol
[cols = ">1,^1,1"]
[frame = "all"]
[grid = "rows"]
[%autowidth]
|===
|`Response`|`::=`|`"l"` `Chunk` `Exit` `"e"`
|`Chunk`|`::=`|`"6:stdout"` `Ben-string`
|`Chunk`|`::=`|`"6:stderr"` `Ben-string`
|`Exit`|`::=`|`"8:exitcode"` `Ben-integer`
|===
