[.text-justify]
= Daiyousei

:source-highlighter: rouge

== Arguments
== Communication
All communication is encoded in the https://en.wikipedia.org/wiki/Bencode[Bencode] encoding.
Both parties communicate by sending a single list to each other.
The start of the list means initiating communication and the list end means proper termination of communication.
The list contains key-value pairs, similar to a dictionary but the keys can be repeated.

=== From client to server
The following data is sent once immediately at program startup.
[cols = 3]
[%autowidth]
|===
|Key|Type|Description

|`argv`|`List<String>`|Commandline arguments intended for passing
|`cwd`|`String`|Current working directory
|`env`|`Dictionary<String>`|Environment variables
|===

The following data is streamed and can be sent multiple times.
[cols = 3]
[%autowidth]
|===
|Key|Type|Description

|`stdin`|`String`|Standard input data chnuk
|===

=== From server to client
The server sends the following data to the client.
[cols = 3]
[%autowidth]
|===
|Key|Type|Description

|`stdout`|`String`|Standard output data chunk
|`stderr`|`String`|Standard error output data chunk
|`exitcode`|`Integer`|Exit code
|===

Standard outputs are streamed in chunks and can be interleaved in repeated.
The exit code value will be returned by the client unless a different error is encountered by the client.
The server can still continue to communicate after sending the exit code and must still properly terminate the communication.
