name: Continuous Integration
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container: quay.io/centos/centos:stream9
    env:
      CXX: g++
      CXXFLAGS: -Werror -g -Wall -Wextra -Wpedantic -fsanitize=undefined,address -D_GLIBCXX_ASSERTIONS -D_GLIBCXX_DEBUG
      LDFLAGS: -fsanitize=address,undefined
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          dnf -y install epel-release
          dnf -y install diffutils gcc-toolset-13-gcc-c++ gcc-toolset-13-libasan-devel gcc-toolset-13-libubsan-devel make-latest rubygem-asciidoctor
      - name: Compile
        run: |
          source /opt/rh/gcc-toolset-13/enable
          source /opt/rh/make*/enable
          make -j8 test-compile doc manpages
      - name: Run unit tests
        run: |
          source /opt/rh/gcc-toolset-13/enable
          source /opt/rh/make*/enable
          make test-unit
      - name: Run integration tests
        run: |
          source /opt/rh/gcc-toolset-13/enable
          source /opt/rh/make*/enable
          make test-server
